# Generated by Django 4.0 on 2022-01-07 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plano: ')),
                ('descri', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição: ')),
            ],
        ),
        migrations.CreateModel(
            name='CadastroFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome: ')),
                ('data', models.DateTimeField(verbose_name='Data: ')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço: ')),
                ('contato', models.CharField(max_length=150, verbose_name='Telefone: ')),
                ('plano_solicitado', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.clienteplano')),
            ],
        ),
        migrations.CreateModel(
            name='CadastroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome: ')),
                ('data_assinatura', models.DateTimeField(verbose_name='Data da Assinatura: ')),
                ('plano_escolhido', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.clienteplano')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
    ]
